### ISSUE TITLE
"libch32v/lib/src/ch32v00x_dbgmcu.c:50: Error: unrecognized opcode `csrr a0,0x7C0', extension `zicsr' required"

### ISSUE THREAD

**Issue by prosper00** [nj-designs/libch32v#1]
When I try to compile following your README, I get the noted error. The fix is to either use the WCH provided gcc (which I think is 8.x, or, for newer versions of GCC, use '-march=rv32ec_zicsr -mabi=ilp32e' to compile. However, this breaks the linker. So, you need to pass '-march=rv32ec' there.  See https://www.eevblog.com/forum/microcontrollers/risc-v-compilation-errors-mismatched-libgcc/

**Comment by nj-designs** [comment]
> When I try to compile following your README, I get the noted error. The fix is to either use the WCH provided gcc (which I think is 8.x, or, for newer versions of GCC, use '-march=rv32ec_zicsr -mabi=ilp32e' to compile. However, this breaks the linker. So, you need to pass '-march=rv32ec' there. See https://www.eevblog.com/forum/microcontrollers/risc-v-compilation-errors-mismatched-libgcc/

OK, thanks, I'll take a look when I get some time.

**Comment by nj-designs** [comment]
Fixed on main
